title: Cedar Grove Christian
description: A warm, inviting Chuckey church where everyone is welcome and God comes first.
url: "https://cedargrovechristian.com"
baseurl: ""   # empty for a root (user/org) site
logo: /assets/images/logo.png
image: /assets/images/logo.png
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
markdown: kramdown
theme: minima
exclude:
  - node_modules
  - vendor
  - README.md
  - package.json

  # Site data used in templates
service_times:
  main_service: "9:30 AM"
  sunday_school: "10:30 AM"
  wednesday_bible_study: "2025-09-21 18:30"
#  wednesday_study: "2025-08-20 18:30"
  sunday_service: "2025-01-05 09:30"
  wednesday_study: "2025-01-01 18:30"
  wednesday_kids_4_truth: "6:30 PM"
  study_wednesday: "6:30 PM"
address: "5270 Chuckey Pike, Chuckey, TN 37641"
email: "cedargrovechristiantn@gmail.com"
phone: "423-525-7413"
phone_e164: "+14235257413"
facebook: "https://www.facebook.com/profile.php?id=100064446712278"
youtube: "https://www.youtube.com/@CedarGroveChristian"

collections:
  sermons:
    output: false
    permalink: /sermons/:slug/

# Optional: default layout for all sermons
defaults:
  - scope: { path: "", type: sermons }

    values: { layout: sermon }
